[package]
name = "blink"
version = "0.1.0"
authors = ["Torkel Danielsson <torkel@voysys.se>"]
edition = "2018"

[dependencies]
stm32f1 = "0.10.0"
cortex-m-rt = "*"
cortex-m = "*"

[dependencies.stm32f1xx-hal]
path = "../../stm32f1xx-hal"
version = "*"
features = ["rt", "stm32f107", "medium"]
